baseURL = 'https://fusekka.com'
languageCode = 'ja'
title = 'fusekka.com'

# テーマを直接読み込む設定
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params.homeInfoParams]
    Title = "fusekka.com へようこそ"
    Content = "技術で人生を切り拓くログです。"