baseURL = 'https://fusekka.com/'
languageCode = 'ja'
hasCJKLanguage = true
title = 'Fusekka | Tech & Repair'
theme = "github.com/adityatelange/hugo-PaperMod"

[pagination]
  pagerSize = 5

enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
    # Dropbox Techに倣い、清潔感のあるライトモード固定
    defaultTheme = "light"
    disableThemeToggle = true
    
    description = "Cisco, Yamaha, Juniperなどのネットワーク機器ジャンク修理記録。仕入れから修理方法、販売利益まで全てを公開する副業エンジニアブログ。"
    author = "Fusekka"
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true

    # 海外テックサイトの定番フォントセット
    customFontFace = "Inter:wght@400;600;800&family=Zen+Kaku+Gothic+New:wght@400;700&display=swap"

    [params.homeInfoParams]
        Title = "Fusekka"
        Content = """
手取り16万の社畜です。ジャンク修理で小銭を稼いでいます。<br>
このブログを真似するだけで億万長者に！？（なれません）<br><br>
 [記事を見る](/posts) ／ [愛用ツールを見る](/posts/tools)
"""

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Fusekka"
    [[params.socialIcons]]
        name = "x"
        url = "https://x.com/Fusekka"

[[menu.main]]
    identifier = "search"
    name = "SEARCH"
    url = "/search/"
    weight = 10
[[menu.main]]
    identifier = "categories"
    name = "CATEGORIES"
    url = "/categories/"
    weight = 20
[[menu.main]]
    identifier = "tags"
    name = "TAGS"
    url = "/tags/"
    weight = 30

[outputs]
    home = ["HTML", "RSS", "JSON"]
