baseURL = 'https://fusekka.com/'
languageCode = 'ja'
hasCJKLanguage = true
title = 'ジャンク修理ブログ'
theme = "github.com/adityatelange/hugo-PaperMod"

[pagination]
  pagerSize = 5

enableRobotsTXT = true

# HTMLタグ（<br>など）を許可し、改行を有効にする
[markup.goldmark.renderer]
  unsafe = true

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
    defaultTheme = "light"
    disableThemeToggle = true
    author = "Fusekka"
    ShowReadingTime = true
    ShowShareButtons = true
    ShowBreadCrumbs = true

    customFontFace = "Inter:wght@400;600;800&family=Zen+Kaku+Gothic+New:wght@400;700&display=swap"

    [params.homeInfoParams]
        Title = "Fusekka"
        Content = """
手取り16万の社畜です。ジャンク修理で小銭を稼いでいます。<br>
このブログを真似するだけで億万長者に！？（なれません）
"""
        [[params.homeInfoParams.buttons]]
            name = "記事を見る"
            url = "/posts"
        [[params.homeInfoParams.buttons]]
            name = "愛用ツールを見る"
            url = "/posts/tools"

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Fusekka"
    [[params.socialIcons]]
        name = "x"
        url = "https://x.com/Fusekka"

[[menu.main]]
    identifier = "search"
    name = "記事検索"
    url = "/search/"
    weight = 10
[[menu.main]]
    identifier = "categories"
    name = "カテゴリ"
    url = "/categories/"
    weight = 20
[[menu.main]]
    identifier = "tags"
    name = "タグ一覧"
    url = "/tags/"
    weight = 30

[outputs]
    home = ["HTML", "RSS", "JSON"]
