baseURL = 'https://fusekka.com/'
languageCode = 'ja'
hasCJKLanguage = true
title = 'Fusekka | ジャンク修理とその他もろもろブログ'
theme = "github.com/adityatelange/hugo-PaperMod"

# 【ここを修正】Hugo v0.128以降の新しい書き方
[pagination]
  pagerSize = 5

# SEO対策：ロボット用
enableRobotsTXT = true

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
    defaultTheme = "dark"
    disableThemeToggle = true
    
    description = "Cisco, Yamaha, Juniperなどのネットワーク機器ジャンク修理記録。仕入れ額と修理後の販売利益も公開する副業エンジニアブログ。"
    author = "Fusekka"
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true

    [params.homeInfoParams]
        Title = "Fusekka | 最近の投稿"
        Content = """
手取り16万の社畜です。ジャンク修理で小銭を稼いでいます。
このブログを真似するだけで億万長者に！？(なれません)

[過去に修理したもの](/posts) ／ [愛用ツール紹介](/posts/tools)
"""

    [params.profileMode]
        enabled = false

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/Fusekka"
    [[params.socialIcons]]
        name = "x"
        url = "https://x.com/Fusekka"

[[menu.main]]
    identifier = "search"
    name = "SEARCH"
    url = "/search/"
    weight = 10
[[menu.main]]
    identifier = "categories"
    name = "CATEGORIES"
    url = "/categories/"
    weight = 20
[[menu.main]]
    identifier = "tags"
    name = "TAGS"
    url = "/tags/"
    weight = 30

[outputs]
    home = ["HTML", "RSS", "JSON"]
